title: Yi Zhang
description: I am a PhD with National Engineering Research Center for Big Data Technology and System, Services Computing Technology and System Lab, Cluster and Grid Computing Lab, School of Computer Science and Technology in Huazhong University of Science and Technology. I am interested in dynamic graph pattern mining system.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
